### ISSUE TITLE
1.4.5 Review and refine use case diagram and descriptions

### ISSUE THREAD

**Issue by 2202282** [Juicy-Lemonberry/INF2001-P5-2#43]
Tasks: 
- [x] Check the use case diagram #8 
- [x] Check the use case description for Staff #31 
- [x] Check the user case description for IT Admin #41 
- [x] Check the user case description for Manager #42

**Comment by Zhwee** [comment]
Summary:
Checked the use case diagram, checked the use case description for staff, IT admin and Manager, they look correct

Duration: 2 days
Start/end dates: 21/9/23 to 22/9/23
