### ISSUE TITLE
2.4.1 M2 Report

### ISSUE THREAD

**Issue by wqyeo** [Juicy-Lemonberry/INF2001-P5-2#77]
Tasks:
Fill up the following sections of M2 Report:

- [x] Requirements _(Functional, non functional, improve on them based on M1)_
- [x] Class Diagram; Awaiting #71 
- [x] Component Diagram; Awaiting #47 
- [x] Sequence Diagrams; Awaiting #70 
- [x] Improve Use Case Diagram based on M1
- [x] Update Use Case descriptions
- [x] Ensure all information in the report is correct

Goals: Fill up all the above sections in the M2 Report
Completion Criteria: Ensure all sections have been filled up based on the template
Allocated Time: 4 days
Start & End date 23/10/23 - 27/10/23

**Comment by wqyeo** [comment]
![Kyaru_Cook](https://github.com/Juicy-Lemonberry/INF2001-P5-2/assets/25131995/f7be13ce-08af-47d8-9bcb-33c6b8d3eebd)

Cooked up some description for sequence diagram and component diagram on it's current state. Check respective issue on #47 and #70

**Comment by wqyeo** [comment]
M2 Report done with class diagram added respectively check #49, #73 , #71 for details...
